### PR TITLE
show message if config file not found.

### PR DESCRIPTION
**Pull request by craigvl**
Just a small update to inform the user that a config file was not found.

### CODE REVIEW

**Comment by vptes1** [comment]
I wanted to avoid making the CLI output too verbose. If there is demand the other way, however, we'll start adding more output like this. I just want to wait and see.

**Comment by craigvl** [comment]
Ok no worries, also if we use the -- recursive flag should it look for the configuration file in sub directories?

**Comment by vptes1** [comment]
Hmm. I'm going to say that it shouldn't look into subdirectories for the config file because 1) the config file should always be at the top directory, otherwise it's implying that the config only applies to the subdirectory it's in...which leads to 2) what happens if multiple config files are found?

**Comment by craigvl** [comment]
Ok makes sense.

**Pull request closed without merging**
